// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.1
// source: vote.proto

/* eslint-disable */

export const protobufPackage = "";

export const _PACKAGE_NAME = "";
